#!/bin/bash

if [ $# != 1 ]; then
    echo "Usage: $0 <find|file>"
    exit 1
fi

filter_type="$1"
MY_PY_FILE_LINES_FILE=/tmp/my-py-file-lines
MY_PY_FILE_LINES_FILTERED_FILE=/tmp/my-py-file-lines-filtered

# Define the paths to ignore
ignore_paths=(
    "venv"
    "node_modules"
    "site-packages"
    "Application Support"
    "Python/3.6/bin"
    "langchain-examples"
    "spyder-"
    "anthropic/courses"
    "env/bin"
    "dh-consumer/tests"
    "vela-schema-registry-old"
    "serializer/.tox"
    "/old/"
    "workspace-keep"
    "keep/"
    ".hg-git"
    "pgAdmin"
    "tokenator"
    "vscode"
    "plugins"
    "python_scripts"
    "Library"
    "gradios"
    "usr-local-bin"
)


if [ $filter_type == "find" ]; then
    echo "Finding all python files in the current directory and subdirectories, except for ignored_paths."

    # Remove the temporary file if it exists
    rm -f ${MY_PY_FILE_LINES_FILE}

    # Use find to search up to 5 layers deep to list
    # python files owned by the current user
    find_command="find . -type f -name '*.py' -user $(id -u)  -maxdepth 5"

    # append the ignore paths to the find command
    for ignore_path in "${ignore_paths[@]}"; do
        find_command+=" ! -path '*/${ignore_path}/*'"
    done

    # Execute the find command and count lines
    eval "$find_command -exec wc -l {} \; 2> /dev/null" | awk '{print $2, $1}' | tee -a ${MY_PY_FILE_LINES_FILE}

    # Print the results
    total_files=$(wc -l ${MY_PY_FILE_LINES_FILE}) | tr -d ' '
    total_lines=$(awk '{sum+=$2} END {print sum}' ${MY_PY_FILE_LINES_FILE}) | tr -d ' '
    avg_lines_per_file=$(echo "$total_lines / $total_files" | bc -S 2)

    echo "Results tallied from ${MY_PY_FILE_LINES_FILE}"
    
    echo "Total files: $total_files"
    echo "Total lines: $total_lines"
    echo "Lines/File:  $avg_lines_per_file"
fi

# use the latest version of the ignore_paths to re-filter
# ${MY_PY_FILE_LINES_FILE} and store it to
# ${MY_PY_FILE_LINES_FILTERED_FILE}
if [ $filter_type == "file" ]; then
    if [ -n ${MY_PY_FILE_LINES_FILE} ]; then
        echo "Error: ${MY_PY_FILE_LINES_FILE} does not exist. Run the find command first by setting filter_type=find"
        exit 1
    fi

    total_files=$(wc -l ${MY_PY_FILE_LINES_FILE}) | tr -d ' '
    total_lines=$(awk '{sum+=$2} END {print sum}' ${MY_PY_FILE_LINES_FILE}) | tr -d ' '
    avg_lines_per_file=$(echo "$total_lines / $total_files" | bc -S 2)

    echo "Pre-filtered results tallied from ${MY_PY_FILE_LINES_FILE}"

    echo "Total files pre-filtered: $total_files"
    echo "Total lines pre-filtered: $total_lines"
    echo "Lines/File  pre-filtered: $avg_lines_per_file"

    # processing the results from the above find command
    find_command="cat ${MY_PY_FILE_LINES_FILE} "

    # Append the latest version of the ignore paths to the command
    for ignore_path in "${ignore_paths[@]}"; do
        find_command+=" ! -path '*/${ignore_path}/*'"
    done

    echo "find command: $find_command"
    eval "$find_command > ${MY_PY_FILE_LINES_FILTERED_FILE}"

    total_files=$(wc -l ${MY_PY_FILE_LINES_FILTERED_FILE}) | tr -d ' '
    total_lines=$(awk '{sum+=$2} END {print sum}' ${MY_PY_FILE_LINES_FILTERED_FILE}) | tr -d ' '
    avg_lines_per_file=$(echo "$total_lines / $total_files" | bc -S 2)

    echo "Post-filtered results tallied from ${MY_PY_FILE_LINES_FILTERED_FILE}"

    echo "Total files post-filtered: $total_files"
    echo "Total lines post-filtered: $total_lines"
    echo "Lines/File  post-filtered: $avg_lines_per_file"

fi
