#!/bin/bash

# Check if any argument is provided
if [ $# -eq 0 ]; then
    echo -e "\033[1;33mto save disk space, this runs\033[0m"
    echo -e "\033[1;33m'pip uninstall -r requirements.txt'\033[0m"
    echo -e "\033[1;33min the given directory\033[0m"
    echo -e "\033[1;33mUsage: $0 <directory>\033[0m"
    echo
    echo -e "\033[0;32m> for i in workspace-*/*; do ~/bin/pip-clean \"$i\"; done\033[0m"  # Dark Green for successful uninstall
    exit 1
fi

# Directory to check
DIRECTORY="$1"

# Change to the specified directory
cd "$DIRECTORY" || exit

# Check if both 'venv' folder and 'requirements.txt' file exist
if [ -d "venv" ] && [ -f "requirements.txt" ]; then
    # Activate the virtual environment and uninstall packages
    source venv/bin/activate
    
    # Use pip with custom output formatting
    pip uninstall -r requirements.txt -y 2>&1 | while read -r line; do
        if [[ $line == *"Successfully uninstalled"* ]]; then
            echo -e "\033[0;32m$line\033[0m"  # Dark Green for successful uninstall
        elif [[ $line == *"WARNING"* ]]; then
            echo -e "\033[1;33m$line\033[0m"  # Yellow for warnings
        else
            echo "$line"
        fi
    done
else
    echo -e "\033[1;33mEither 'venv' directory or 'requirements.txt' file is missing.\033[0m"
fi
